  PROGRAM EULER32
	IMPLICIT NONE
	REAL :: RC
	INTEGER :: J, BEST
	INTEGER(16) :: NUM
	BEST = 0
	NUM = 600851475143
	RC = INT(SQRT(REAL(NUM))) + 1
!	DO J = 3, INT(RC), 2
	DO J = 3, NUM, 2
		IF(ISPRIME(REAL(J)) .AND. MOD(NUM, J) == 0) THEN
			BEST = J
		END IF
	END DO
	PRINT *, BEST



  CONTAINS 
	FUNCTION ISPRIME(N)
		LOGICAL :: ISPRIME, VAL 
		REAL :: N, SQUARE_ROOT
		INTEGER :: I
		VAL = .FALSE.
		IF (MOD(INT(N), 2) == 0) THEN
			VAL = .FALSE.
			GOTO 10
		END IF 
		SQUARE_ROOT = INT(SQRT(N)) + 1
		DO I = 3, INT(SQUARE_ROOT), 2
			IF (MOD(INT(N), I) == 0) THEN
				VAL = .FALSE.
				GOTO 10
			END IF
		END DO
		VAL = .TRUE.
10	END FUNCTION ISPRIME


  END PROGRAM EULER32
