PROGRAM Euler2
	IMPLICIT NONE
	INTEGER :: CURRENT, NEXT, HOLDER, SU
	CURRENT = 2
	NEXT = 3
	HOLDER = 3
	SU = 0
	DO WHILE (CURRENT < 4000000)
		IF(MOD(CURRENT, 2) == 0) THEN
			SU = SU + CURRENT
		END IF
		HOLDER = NEXT
		NEXT = NEXT + CURRENT
		CURRENT = HOLDER
	END DO
	PRINT *, SU
END PROGRAM Euler2
