  PROGRAM EULER4
	IMPLICIT NONE
	INTEGER :: I, J, BEST, BER
	BEST = 0

  DO I = 100, 999
	DO J = 100, 999
		BER = I*J
		IF(ISPAL(BER) .AND. BER > BEST) THEN
			BEST = BER
		END IF
	END DO
  END DO
  PRINT *, BEST
  PRINT *, ISPAL(1001)
  PRINT *, ISPAL(108)
  PRINT *, (999**2)
  CONTAINS 
	FUNCTION ISPAL(N)
		LOGICAL :: ISPAL, VAL
		INTEGER :: DIGIT, REV, I, N, NUM
		NUM = N
		VAL = .FALSE.
		DO WHILE(NUM > 0)
			DIGIT = MOD(NUM, 10)
			REV = REV * 10 + DIGIT
			NUM = NUM / 10
		END DO 
		IF(N == REV) THEN
			PRINT *, N
			PRINT *, "REV = "
			PRINT *, REV
			VAL = .TRUE.
			GOTO 10
		END IF
		VAL = .FALSE.
10	END FUNCTION ISPAL

  END PROGRAM EULER4
